---
title: "Please select your title"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: Wei
  othernames: Juntong
  address: Monash Universtidy
  email: jwei55@student.monash.edu
  correspondingauthor: true
  qualifications:  Master
- familyname: Xu
  othernames: Qin 
  address: 40 Carboni crescent 
  email: qxuu0023@student.monash.edu
  correspondingauthor: true
  qualifications:  Mbat
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
```



\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}
```{r}
library(tidyverse)
library(kableExtra)
```

```{r}
dat <- read.csv("Assignment3_data.csv")
dat1 <- dat %>%
  filter(Country_Name %in% c("China",
                             "Japan")) %>%
  group_by(Country_Name) %>%
  summarise(CO2 = sum(CO2_emissions_metric_tons_per_capita))
kable(dat1)
```

\section*{Country XX3 and YY3}

```{r}
data <- read.csv("Assignment3_data.csv") %>% 
  filter(Country_Name == "Japan" | Country_Name == "Australia") %>% 
  group_by(Country_Name)
data
#df <- data %>% 
  #summarise(Average_population = mean(Urban_population))
#df
```
The result of this table illustrate that ......

\section*{Country Australia and India}

```{r}
knitr::opts_chunk$set(echo = FALSE, 
                      cache = FALSE, 
                      cache.lazy = FALSE,
                      eval = TRUE,
                      fig.align= "center")

```

```{r loading libraries, message = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(dslabs)
library(kableExtra)
library(bookdown)
library(knitr)
```

```{r}
data <- read.csv("Assignment3_data.csv")
head (data)
glimpse(data)
dim(data)
```

## Comparsion of OF CO2 emission between Australia and India


```{r}
countries <- data %>% 
  group_by(Country_Name) %>% 
    filter (Country_Name == "Australia" | Country_Name == "India" ) %>% 
  select(c("Country_Name","CO2_emissions_metric_tons_per_capita")) %>% 
  summarise (CO2_emissions_metric_tons_per_capita = sum(CO2_emissions_metric_tons_per_capita, na.rm=TRUE)) %>% 
  arrange(desc(CO2_emissions_metric_tons_per_capita))
countries 

knitr::kable (countries ,caption = "The total CO2_emissions_metric_ton_per_capita from 1960 to 2014 for both Australia and India") %>% kable_styling()
```
In Table \@ref(tab:table1) we compare the total CO2 emissions metric tons per capita  

